server {
    server_name             first_webserv;
    listen                  8080;
    host                    localhost;
    client_max_body_size    10 000 000;

    root                    www;
    error_page 404          error_404.html;

    location  {
        default             index.html
        allowed_methods     GET 
        autoindex           off
    }
	location /github{
		return 301 https://github.com/sorbiii
	}
}

server {
    server_name             second_webserv;
    listen                  8088;
    host                    127.0.0.1;
    client_max_body_size    10 000 000;

    root                    www;
    error_page 404          404.html;

    location / {
        allowed_methods     GET POST DELETE
        autoindex           on
    }

    location /uploads {
        default             index.html
        allowed_methods     GET POST DELETE HOP
    }

    location /cgi-bin {
        cgi .py /usr/bin/python3
        allowed_methods     GET POST DELETE
    }
}
