
server_name             first_webserv;
listen                  8080;
host                    localhost;
client_max_body_size    10 000 000;

root                    www;
error_page 404          error_404.html;

location  {
    default             index.html
    allowed_methods     GET 
    autoindex           off
}
location /github{
	return 301 https://github.com/sorbiii
}