server {
    listen 8080;
    host 127.0.0.1;
    server_name eval_server;
	root public;
    
    # 1. / must answer to GET request ONLY
    location / {
        allowed_methods GET
    }

    # 2. Any file with .bla as extension must answer to POST request by calling the cgi_test executable
    location *.bla {
        allowed_methods POST
        cgi .bla ubuntu_cgi_tester 
    }

    # 3. /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        allowed_methods POST
    }

    # 4. /directory/ must answer to GET request and the root of it would be the repository YoupiBanane...
    location /directory/ {
        allowed_methods GET
        default youpi.bad_extension
    }
}