server {
    server_name             eval_server;
    listen                  8080;
    host                    localhost;
    client_max_body_size    1000000;

    root                    public;
    error_page 404          error_404.html;

    # / must answer to GET request ONLY
    location / {
        allowed_methods     GET
        autoindex           off
    }

    # Any file with .bla extension must answer to POST by calling cgi_test
    location /cgi-bin {
        allowed_methods     POST
        cgi .bla             /path/to/cgi_test
    }

    # /post_body must answer anything to POST, with a max body of 100
    location /post_body {
        allowed_methods      POST
        client_max_body_size 100
    }

    # /directory/ must answer to GET, root is YoupiBanane,
    # default file is youpi.bad_extension
    location /directory/ {
        root                YoupiBanane
        default             youpi.bad_extension
        allowed_methods     GET
    }
}